<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="myStore" duration-ms="20384" started-at="2019-09-14T11:44:13 IDT" finished-at="2019-09-14T11:44:33 IDT">
    <groups>
    </groups>
    <test name="Login Test" duration-ms="20384" started-at="2019-09-14T11:44:13 IDT" finished-at="2019-09-14T11:44:33 IDT">
      <class name="com.myStore.testCasses.TC_LoginTest_001">
        <test-method status="PASS" signature="setExtent()[pri:0, instance:com.myStore.testCasses.TC_LoginTest_001@a7e666]" name="setExtent" is-config="true" duration-ms="200" started-at="2019-09-14T11:44:13 IDT" finished-at="2019-09-14T11:44:13 IDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setExtent -->
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:com.myStore.testCasses.TC_LoginTest_001@a7e666]" name="setup" is-config="true" duration-ms="10960" started-at="2019-09-14T11:44:13 IDT" finished-at="2019-09-14T11:44:24 IDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:com.myStore.testCasses.TC_LoginTest_001@a7e666]" name="loginTest" duration-ms="8105" started-at="2019-09-14T11:44:24 IDT" finished-at="2019-09-14T11:44:32 IDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.myStore.testCasses.TC_LoginTest_001.loginTest(TC_LoginTest_001.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.myStore.testCasses.TC_LoginTest_001@a7e666]" name="tearDown" is-config="true" duration-ms="7" started-at="2019-09-14T11:44:32 IDT" finished-at="2019-09-14T11:44:32 IDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=FAILURE method=TC_LoginTest_001.loginTest()[pri:0, instance:com.myStore.testCasses.TC_LoginTest_001@a7e666] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.myStore.testCasses.TC_LoginTest_001@a7e666]" name="tearDown" is-config="true" duration-ms="681" started-at="2019-09-14T11:44:32 IDT" finished-at="2019-09-14T11:44:33 IDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:com.myStore.testCasses.TC_LoginTest_001@a7e666]" name="endReport" is-config="true" duration-ms="390" started-at="2019-09-14T11:44:33 IDT" finished-at="2019-09-14T11:44:33 IDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- com.myStore.testCasses.TC_LoginTest_001 -->
    </test> <!-- Login Test -->
  </suite> <!-- myStore -->
</testng-results>
